### ISSUE TITLE
Anmerkungen / Fragen zum CSI

### ISSUE THREAD

**Issue by leon-richardt** [leon-richardt/location-based-recommendations#1]
@johanneslatzel @hegerdes 

#### `ClientConfiguration`
- Welche Einheit hat `radius`?

#### `Event`
- Start- und Endzeiten?
- Wollen wir `genres` als `Genre[]` oder als eventuell als `List<Genre>` verwalten? Somit könnte der Promoter noch nachträglich Genres ändern, ohne ein neues Event erstellen zu müssen.
- `description` und `name` mutable machen? Dann müsste man zwar in den Gettern eine Deep Copy returnen, und Setter hinzufügen. Aber so können Promoter noch nachträglich die Beschreibung ändern. Anhand der `id` können wir die Events sowieso eindeutig zuordnen.

#### `Genre`
- Wie stellen wir sicher, dass ein Genre immer die selbe `id` hat? (Vielleicht über ´hashCode()` oder über eine Lookup Table?)

#### `ServerConnection`
- Der `ObjectOutputStream` in `writeQuery()` muss wieder geschlossen werden.

#### `EventScoreCalculator`
- Genauer spezifizieren, in welchem Rahmen der Score liegen darf.

#### `ScoredEvent`
- Im Konstruktor sicherstellen, dass der übergebene Score gültig ist.

#### `LBRServer`
- Der `ObjectInputStream` in `answerRequest()` muss wieder geschlossen werden.

**Comment by johanneslatzel** [comment]
`ClientConfiguration`

- km, passe ich noch in den Kommentaren an, sodass es erkenntlich ist

`Event`

- Start- und Endzeit dürfen wir weg lassen. Wir gehen also davon aus, dass unsere Events immer stattfinden, damit die Prozesse erleichtert werden.

`Genre`

- Kannst du bitte ausführen, was genau du erreichen möchtest und wozu das dann genutzt wird?


Den Rest passe ich heute Abend entsprechend deiner Beschreibungen an.

**Comment by leon-richardt** [comment]
Zu Genre:
Mir ist gerade wieder eingefallen, dass wir die Genres ja sowieso nur über eine Drop-Down-Liste zeigen. Kannst den Punkt also ignorieren. 👍

**Comment by johanneslatzel** [comment]
Ich habe die Anpassungen durchgeführt. Siehe diffs. Bitte prüfen.

**Comment by leon-richardt** [comment]
Sieht gut aus! :+1:
