### ISSUE TITLE
Events werden nach einiger Zeit nicht mehr gefetcht - Nach Neustart des Servers funktioniert es wieder

### ISSUE THREAD

**Issue by leon-richardt** [leon-richardt/location-based-recommendations#13]
Aus noch unbekannten Gründen funktioniert nach einiger Zeit das Abholen von Events vom Server nicht mehr. Erst nach einem Neustart des Servers können die Events wieder gefetcht werden.
Die `EventStore`-Query gibt `QueryResultState.OK` zurück.
Woran könnte das liegen und wir können wir das beheben?

**Comment by johanneslatzel** [comment]
eine mögliche ersache könnte ein timeout der db für die DBConnection sein, wenn eine Weile keine SQL-abfragen stattgefunden haben. hierfür wird logging in den LBRServer eingebaut, um herauszufinden, ob es einen zeitlichen oder anderen kausalen zusammenhang gibt.

**Comment by johanneslatzel** [comment]
logging eingebaut und auf pi gestartet - warten auf nächsten fehler, um logs auszuwerten

**Comment by johanneslatzel** [comment]
funktioniert doch noch nicht ganz. exit im terminal kommt sich mit exit der test-schleife in die quere. morgen gehts weiter. erstmal wieder master-version deployed.

**Comment by johanneslatzel** [comment]
lbrserver mit logging ist nun aktiv. ich habe das schließen der ressourcen lbrserver und filehandler über einen shutdownhook umgesetzt

**Comment by johanneslatzel** [comment]
reconnect der DBConnection löst das problem
