### ISSUE TITLE
DBConnection wird nie geschlossen

### ISSUE THREAD

**Issue by johanneslatzel** [leon-richardt/location-based-recommendations#15]
weil die Verbindungen zur DB nur statisch hinterlegt werden, können wir die Verbindung so nur schwer kontrollieren. am besten wäre es eigtl, wenn wir richtig OO arbeiten würden, also auch die DB-Schnittstelle mit richtigen Objekten abbilden und vor allem das Aufbauen/Schließen von Verbindungen richtig handlen.
Es empfiehlt sich außerdem, eine DB-Verbindung nur solange offen zu halten, wie sie gebraucht wird. Auch wenn das bedeutet, dass dann die nächst-erste Verbindung neu aufgebaut werden muss und somit etwas langsamer ist.

**Comment by johanneslatzel** [comment]
momentan ist der stand, dass die db verbindungen nie geschlossen werden. das ist schlecht.

**Comment by hegerdes** [comment]
Soll ich DoQery einfach nicht statisch machen? Dann musst du aber entscheiden wenn es sinnvoll ist DBConnection zu schließen oder neu zu initialisieren

**Comment by johanneslatzel** [comment]
Integrier doquery am besten komplett in dbconnection und mach die Methoden aus doquery private in dbconnection. Implementiere dann in dbconnection closeable. Dann brauch ich ggf nur eine neue dbconnection erzeugen und die alte schließen.

Mit freundlichen Grüßen,

Johannes B. Latzel

________________________________

**Comment by hegerdes** [comment]
Ist erledigt. Aber nicht zu oft die Verbindung schließen. Das aufbauen übers Internet hat echt 1.5 sek gedauert. Ob das bei LocalHost viel schneller ist weiß ich nicht. Hat auch die eingebaute Methode reconnect falls nur ein mal ein Fehler auftritt

**Comment by johanneslatzel** [comment]
Ist gut. Ich werde das reconnect auf jeden Fall nutzen, solange das geht. Dauert auch über local host so lange. Danke.


Mit freundlichen Grüßen,

Johannes B. Latzel

________________________________

**Comment by johanneslatzel** [comment]
close wird im LBRServer aufgerufen
