### ISSUE TITLE
"Periodische" Events hinzufügen

### ISSUE THREAD

**Issue by leon-richardt** [leon-richardt/location-based-recommendations#20]
Ein (oder im Idealfall sogar mehrere) Event(s) so gestalten, dass sie im regelmäßigen Rythmus für den `EventStore` sichtbar und unsichtbar werden. Die Wechsel sollten schnellstens alle 30 Minuten stattfinden.

**Comment by johanneslatzel** [comment]
in [21](https://github.com/leon-richardt/location-based-recommendations/pull/21) umgesetzt. werde ich nachher auf server übertragen.

**Comment by johanneslatzel** [comment]
funktioniert
