### ISSUE TITLE
LBR_CSI_LBRServer_Review2

### ISSUE THREAD

**Issue by johanneslatzel** [leon-richardt/location-based-recommendations#5]
Bitte Branch LBR_CSI_LBRServer_Review2 prüfen. Es wurde hinzugefügt:

- Filter-Funktion nach Genres im LBRServer
- obere Grenze für ClientConfiguration#radius
- Erweiterung Assurance
- Venue um initialDistance aus der DB erweitert

**Comment by leon-richardt** [comment]
Wieso machst du das eigentlich als Issue und nicht gleich als Pull Request? 🤔

**Comment by johanneslatzel** [comment]
pull erstellt
